mqtt:
  image: eclipse-mosquitto
  ports:
    - 1883:1883
    - 8883:8883
    - 9001:9001
  volumes:
    - ./config:/mosquitto/config
    - ./data:/mosquitto/data
    - ./var/log/mosquitto:/mosquitto/log
